### ISSUE TITLE
Functionality to auto focus search/filter box on pop-up

### ISSUE THREAD

**Issue by chocmake** [LonMcGregor/LinksPanel#6]
After using the extension for close to 100 pages so far one QoL UI feature that would be beneficial is auto focusing the filter box when the extension icon is clicked and the pop-up loads.

That way it would save the user an extra click for interactions. Been liking it so far, thanks!

**Comment by LonMcGregor** [comment]
This should now be implemented in v1.3.0.
It may be a short while before the webstore validates and pushes the update.
